### PR TITLE
Update scrolling of next button to match scrolling of navigation

### PR DESCRIPTION
**Pull request by indytechcook**
This is a iteration of #103 

I updated how the scrolling is executed based upon #106 

@tladendo @vietnogi

### CODE REVIEW

**Comment by vietnogi** [comment]
I just noticed that we are using a new component/tag "next-state".  Do we need this extra tag?  Can we use an attribute instead?

**Comment by vietnogi** [comment]
Also, shouldn't the scrollTo occur after the form has been validated and submitted instead of on click?

**Comment by tladendo** [comment]
@vietnogi -- I updated this directive so that it syncs with validation.

**Comment by tladendo** [comment]
lgtm

**Comment by indytechcook** [comment]
This is no longer needed

**Pull request closed without merging**
