### PR TITLE
[DEM-252] Should be able to use enter key after selecting type

### PR DESCRIPTION
**Pull request by vietnogi**
ping @appirio-tech/demandside

### CODE REVIEW

**Comment by tladendo** [comment]
@vietnogi -- this isn't working for me. i should be able to press enter to do 'next' when i'm on the type field, right?

**Comment by vietnogi** [comment]
@tladendo you have to select and be focused on the button

**Comment by tladendo** [comment]
still not working for me, not sure what's up.

**Comment by vietnogi** [comment]
@tladendo crap, donts work on FF

**Comment by vietnogi** [comment]
@tladendo should be fixed

**Comment by tladendo** [comment]
yep works great now

**Pull request merged**
