### PR TITLE
pre-demo fixes

### PR DESCRIPTION
**Pull request by tladendo**
ping @appirio-tech/demandside

### CODE REVIEW

**Comment by indytechcook** [comment]
lgtm.  I don't get the warnings.

**Comment by vietnogi** [comment]
lgtm

**Comment by indytechcook** [comment]
@tladendo looking at this again, I"m not sure that setting is used.  I'm going to just remove the toastr lines

**Comment by indytechcook** [comment]
Merging for Tom since is unavailable.

**Pull request merged**
