### PR TITLE
[DEM-307] Fix Gulp to not crash from a jade/scss compile error

### PR DESCRIPTION
**Pull request by vietnogi**
ping @appirio-tech/demandside

### CODE REVIEW

**Comment by tladendo** [comment]
lgtm

**Comment by tladendo** [comment]
@vietnogi -- actually can you make it so that this shows the file that's causing the error?

**Comment by tladendo** [comment]
oops already closed. if you know how, maybe give it a shot. else i'll look into when i wrap up some other stuff.

**Comment by vietnogi** [comment]
it should show the file that is causing the error

**Pull request merged**
