### PR TITLE
[DEM-129] "What features will your app need?" Page

### PR DESCRIPTION
**Pull request by vietnogi**
ping @tladendo & @indytechcook

### CODE REVIEW

**Comment by vietnogi** [comment]
/#/submit-work/features made changes from wireframes

**Comment by tladendo** [comment]
@vietnogi -- can you reconcile this w/ the changes i made to features? obviously pick your template stuff over mine. also i'm afraid this template is bugging out for me – that image pops up and won't go away.

**Comment by vietnogi** [comment]
@tladendo, is there a particular thing that is missing so I don't have to guess around.  Also, the modal is there to show you the feature.  If it wasn't visible, you wouldn't know it exists.  You would have to add the logic in the controller.  You can add some in page css to hide the the layers in the mean time.

**Comment by tladendo** [comment]
@vietnogi -- I can work with what's here, I just meant that it wasn't merging cleanly. lgtm, please merge when ready

**Pull request merged**
