### PR TITLE
Add terms and conditions as separate page and link from estimate step. DEM-202

### PR DESCRIPTION
**Pull request by tifletcher**

### CODE REVIEW

**Comment by tifletcher** [comment]
PR updated -- what this does is show the terms and conditions on hover using the same mechanism we use to preview features. I've left a standalone route in there on click.

@tladendo @vietnogi Comments?

**Comment by indytechcook** [comment]
lg

**Comment by vietnogi** [comment]
lets not merge this in, going to use a normal modal window for this

**Comment by tladendo** [comment]
@vietnogi -- you're tackling this one, then?

**Comment by vietnogi** [comment]
sure

**Comment by vietnogi** [comment]
Closing in lieu of https://github.com/appirio-tech/ap-work-client/pull/149

**Pull request closed without merging**
