### PR TITLE
Base API resource

### PR DESCRIPTION
**Pull request by indytechcook**
@tladendo and @vietnogi 

I wanted to show you the direction I was going.  I'm adding tests now.

This is a factory for creating resources. It would be used like this:

First, the individual services would register themselves with the API:

```javascript

api.add('work');

// OR

api.add({
  resource: 'work',
  url: '/work'
});

// OR

api.add({
  resource: 'work',
  url: '/users/:user_id/work',
  params: {
    user_id: '@user_id'
  }
});

```

Then api service would be used like this in a controller:

```javascript

api.work.get.$promise.then(function () {});

```

Next I'm adding a data provider which can be used to resolve in routes.

### CODE REVIEW

**Comment by tladendo** [comment]
This is a cool idea. Did you copy this from somewhere? Also, wouldn't it be used in a controller like this: `api.work.get().then(function() {});`?

**Comment by indytechcook** [comment]
I'm not to proud to say I did get the idea from someone else:  http://www.objectpartners.com/2014/06/03/extending-angulars-resource-service-for-a-consistent-api/.

I actually shopped a few different ideas.  Some dealt with extending references, others involved adding decorators.  This method seemed like the simplest, most straightforward and easiest to communication :)

**Comment by tladendo** [comment]
I like this. Seems like a cool idea. lgtm – or you can wait to merge until you have more built

**Comment by vietnogi** [comment]
Seems good, can't see any red flags.  Lets see how this goes.

**Pull request merged**
