### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by vietnogi**
ping @indytechcook & @tladendo

### CODE REVIEW

**Comment by tladendo** [comment]
@vietnogi -- given the change in what we're building, do we still want these changes?

**Comment by vietnogi** [comment]
@tladendo maybe not, going to keep it open for a little longer.

**Comment by vietnogi** [comment]
@tladendo this PR is needed, updated a little, please review in order to merge.

**Comment by tladendo** [comment]
lgtm, go ahead and merge once conflicts are resolved

**Pull request merged**
